services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: mka
      POSTGRES_PASSWORD: mka
      POSTGRES_DB: medical_knowledge_assistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql+psycopg2://mka:mka@postgres:5432/medical_knowledge_assistant
    depends_on:
      - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
